name: Python package

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v9.7.3

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: build with pyinstaller
        run: |
          cd files
          pyinstaller --onefile -w gui.py